### ISSUE TITLE
Import rule `rxjs/operators` vs `rxjs`

### ISSUE THREAD

**Issue by timdeschryver** [cartant/eslint-plugin-rxjs#101]
Hi Nicholas, I hope you're doing fine.

RxJS v7 allows us to import operators directly from `rxjs`.
Sadly, a lot of Angular projects are still using RxJS v6, while many libraries already have migrated to v7.
These libraries try to support both versions of RxJS, which is fine for most of the time.
But it can also lead to breaking changes, for example, when a library author forgets about this and imports an operator from `rxjs` this would mean that it will throw for a consumer that's still on v6.

What's your opinion on creating a (configurable) rule that enforces how operators should be imports, either from `rxjs`, or from `rxjs/operators`. This would solve the above problem, and it would also be handy to enforce a consistent import behavior.

**Comment by lundmikkel** [comment]
It would be nice to be able to forbid the whole `rxjs/operators` namespace, so you could only import from `rxjs` directly.

**Comment by timdeschryver** [comment]
This can be implemented with the ESLint no-restricted-import rule.
For an example see, https://gist.github.com/timdeschryver/85ce798a28d8def0c33f34e67ec64b59
