### ISSUE TITLE
Typescript 5.0.0 Support?

### ISSUE THREAD

**Issue by AnWeber** [cartant/eslint-plugin-rxjs#109]
Could you please provide a version with Typescript 5 support? Your peerDependencies settings prevents using a updated version

**Comment by vinayakpatil** [comment]
@AnWeber this is partially fixed, I still see below dependency issues.

warning "eslint-plugin-rxjs > eslint-etc@5.1.0" has incorrect peer dependency "typescript@^4.0.0".
warning "eslint-plugin-rxjs > tsutils-etc@1.4.1" has incorrect peer dependency "typescript@^4.0.0".

**Comment by AnWeber** [comment]
@vinayakpatil It works for me. You need to use tsutils@1.4.2 and eslint-etc@5.2.1, Both uses `typescript: >4.0.0` as peer Dependency.
