### ISSUE TITLE
Rule to top-level catchError's in epics

### ISSUE THREAD

**Issue by connor4312** [cartant/eslint-plugin-rxjs#37]
I noticed you had some rules around epics, and thought I'd suggest one (that we've written a custom tslint rule for in the past.) If you have an epic like this...

```ts
const myEpic = actions =>
  actions.pipe(
    filter(isGetDataAction),
    switchMap(action => myApi.getData(action.payload)),
    catchError(err => of(showMyErrorAction())),
  );
```

...then when you first get an error, catchError() will handle it but the epic will be faulted, so further `getDataAction`s won't do anything. This is rarely (never?) something desirable, so we have a rule to prevent it.

**Comment by cartant** [comment]
Yeah, I that's what the [`no-unsafe-catch`](https://github.com/cartant/eslint-plugin-rxjs/blob/master/source/rules/no-unsafe-catch.ts) rule guards against:

https://github.com/cartant/eslint-plugin-rxjs/blob/5993893a9b60af9f1751aa8e5dfed9625156bd88/tests/rules/no-unsafe-catch.ts#L111-L126

Maybe that's not obvious from the rule's name, but, hey, naming things is hard. 😅

**Comment by connor4312** [comment]
Ah, nice! I scanned through the test cases to see what was happening and it looked like it was testing for `() => EMPTY`. I'll close the issue out then, nice work on this library :)

**Comment by cartant** [comment]
No worries. Suggestions are always welcome - and contributions, too! - so if you have any, please open an issue.
