### ISSUE TITLE
Create a shareable eslint-plugin-rxjs:recommended config

### ISSUE THREAD

**Issue by the-ult** [cartant/eslint-plugin-rxjs#40]
It would be nice if a recommended settings preset would be available.
Which could be separately installed and extended

Like:
- [eslint-plugin-jest](https://github.com/henningmu/eslint-plugin-jest#shareable-configurations)
- [eslint-plugin-unicorn](https://github.com/sindresorhus/eslint-plugin-unicorn#recommended-config)
- etc

**Comment by cartant** [comment]
This will happen, but not before both this package and `rxjs-tslint-rules` are moved into the official RxJS repo - which will become a monorepo. At that stage, the core team will decide upon a recommended rule set.

**Comment by the-ult** [comment]
Cool, very good the hear that this project will be part of the official RxJS repo. Well done
