### ISSUE TITLE
Publish a 0.0.2-beta or unpublish 0.0.1-beta.3clear

### ISSUE THREAD

**Issue by rassie** [cartant/eslint-plugin-rxjs#42]
Disclaimer: Since `eslint-plugin-rxjs` is in your-own-risk-deep-beta phase, this issue is obviously neither urgent nor important, but maybe you were looking for an excuse to bump the version number anyway, so here's one for you :)

The issue is that based on `node-semver` `0.0.1-beta.3clear` apparently is always the highest in `0.0.1-beta` series, thus everything using `node-semver` will ignore anything higher and even propose a downgrade. See https://github.com/renovatebot/renovate/issues/4854 for my original problem and https://github.com/npm/node-semver/issues/297 for the root cause.

**Comment by cartant** [comment]
Thanks for pointing this out. I've published `0.0.2-beta.11`.
