### ISSUE TITLE
Idea for naming observables ?

### ISSUE THREAD

**Issue by iangregsondev** [cartant/eslint-plugin-rxjs#44]
Hi,

It would be great if you could set a rule to say that observables should be suffixed with the $ sign

I know not everyone uses this naming convention but it is almost a recognised standard in the community.

Of course, you could turn it off or on.

Do you plan on adding something like this ?

Thanks in advance

**Comment by cartant** [comment]
See `rxjs-finnish` in https://github.com/cartant/eslint-plugin-rxjs/issues/7

**Comment by iangregsondev** [comment]
Thanks @cartant , I wil close that. I missed it in the other repo.
