### ISSUE TITLE
no-topromise

### ISSUE THREAD

**Issue by lucasteles** [cartant/eslint-plugin-rxjs#45]
Would be nice a rule that dont allow us to write toPromise() in observables

**Comment by cartant** [comment]
Yeah, I think that would be useful.

**Comment by cartant** [comment]
Assigned this to myself, but if you wanna implement it and open a PR, that would be great.

**Comment by cartant** [comment]
`eslint-plugin-rxjs@0.0.2-beta.16` should have a `no-topromise` rule in it.

**Comment by lucasteles** [comment]
Sorry, I saw your reply Just now.

A think we only miss the rule in the readme
