### ISSUE TITLE
Rule to enforce parameter type declaration of `unknown` for catchError()

### ISSUE THREAD

**Issue by felixfbecker** [cartant/eslint-plugin-rxjs#49]
The time has finally come that [TypeScript v4 added the ability to explicitly declare `catch` bindings as `unknown`](https://devblogs.microsoft.com/typescript/announcing-typescript-4-0-beta/#unknown-on-catch) instead of `any` and the next version of `typescript-eslint` [will come with a rule to enforce the usage of `unknown` for all `catch` clauses](https://github.com/typescript-eslint/typescript-eslint/pull/2202), finally making them type safe.

The only puzzle piece missing then is the same for `catchError()` bindings in Rx. These are `any` in the typings by default (the same as with TypeScript v4's `catch` clauses), but them being `any`, they can be manually declared to be `unknown` instead. It would be awesome to have a rule that enforces this, with an autofixer. It should also forbid any other types to be used (those can be explicitly casted if needed).

**Comment by cartant** [comment]
There is now a `no-implicit-any-catch` rule in this package - to handle `catchError` operators - and there's a `no-implicit-any-catch` rule in `eslint-plugin-etc`, too - to handle promise rejections in `catch` and `then` calls.
