### ISSUE TITLE
Node.js v10 support

### ISSUE THREAD

**Issue by jdanil** [cartant/eslint-plugin-rxjs#52]
Hey there 👋 

I'm running one of my repos against LTS versions of node in CI and just noticed that it is failing in node 10 because of the engines requirement in this package.

I'm just wondering if there is are features being used here that specifically require node >=12 or if support for 10 is possible too.

Node 10 is still getting maintenance support until April next year.
https://github.com/nodejs/Release#release-schedule

**Comment by cartant** [comment]
When I first published these ESLint rules packages, I'd copied the TypeScript configuration from one of my library repos and on those I perform no downleveling - I leave that to the consumer.

I've been using Node 14, so it was not effecting any errors for me, but it broke a user who was on Node 12, so I set that as the limit in the `package.json` and downleveled to ES2019. Lowering the limit to Node 10 and downleveling to what looks like [ES2018](https://node.green/#ES2018) should be no big deal. I'll have a look at getting it done today or tomorrow. If you want it done sooner, you can open a PR. The `package.json` and the `tsconfig.json` file are all that you'd need to change.

**Comment by jdanil** [comment]
Its all good. I'm not in any hurry. I raised a PR if its useful.
For what its worth I used nvm to switch my node version to v10 and ran `dist` and `test`.
All looked to be working.

**Comment by cartant** [comment]
Thanks. I've just solved the TypeScript problem that has been bugging me all day, and I have the time - and I'm in the mood - to do something straightforward - like a package release - so I'll do it now.

**Comment by cartant** [comment]
Done.

**Comment by jdanil** [comment]
Awesome. Thanks for the quick release!
