### ISSUE TITLE
Allow tap operator after takeUntil

### ISSUE THREAD

**Issue by willium** [cartant/eslint-plugin-rxjs#55]
Give that `tap`'s contract is that it can perform side effects but returns an identical Observable, is it not safe to follow a `takeUntil` with a `tap` (and thus allow it [here](https://github.com/cartant/eslint-plugin-rxjs/blob/main/source/rules/no-unsafe-takeuntil.ts#L51))

e.g.

```ts
const stream$ = of().pipe(
    ...
    takeUntil(unsubscribe$),
    tap((datasets) => { setSomeState(true) })
)
```

**Comment by cartant** [comment]
That's not the point of the rule, though. The idea is that `takeUntil` ought to be placed as the last operator in the pipeline unless there is a compelling reason to not do so. There's no reason the `tap` cannot be placed before the `takeUntil`.

**Comment by willium** [comment]
Well in this case, if the `tap` were before it could cause a state update on an unmounted component, no?

**Comment by cartant** [comment]
No. When the `takeUntil` notifier emits, the pipeline will unsubscribe

**Comment by willium** [comment]
Ah—even if its in the middle of executing the pipeline (and the `tap`) operator?

**Comment by cartant** [comment]
Well, there's only one thread - for which I'm kinda grateful, TBH.

**Comment by cartant** [comment]
If the `tap` was using a `complete` callback, it would behave differently, though. In that case, you might want to disable the rule locally using an `/* eslint-disable-next-line ... */` comment. A lot these rules try to help devs by performing some static analysis to find things that might be problematic, but if you find a situation that warrants it, disable the rule locally.

**Comment by willium** [comment]
Ha—appreciate your help! It sounds like I'm just missing something—or thinking too imperatively—but by my read it seems like the side effects in the `tap` would occur before the pipe "gets" to the `takeUntil` and thus "checks" to see that the notifier hadn't emitted... but now writing that here it seems like I've got pipes backwards... that the notifier would `emit` when the `.next()` and `.complete()` calls are made. As you said, there is only 1 thread, and it's not possible that there was some kind of race condition. Is that right?

**Comment by cartant** [comment]
> ... and it's not possible that there was some kind of race condition. Is that right?

Yeah, there's no race here, the unsubscription is synchronous.

**Comment by willium** [comment]
> A lot these rules try to help devs by performing some static analysis
Totally! I'm a relative newcomer to RxJS, so I don't want to go turning off listing rules that make sense unless I understand them. Despite the fact that you've now, convinced me it's not _possible_ for the side-effects in a `tap` proceeding a `takeUntil` to cause problems, it still _feels_ like the eslint rule could allow for `tap` operators to follow a `takeUntil` as it seems to not have any adverse effects or leaky cases? It feels a bit wrong for the linting rule to be more strict than the contract we have with the tap function not to effect the Observable at all, no?

**Comment by cartant** [comment]
It's essentially the way it is 'cause it's easier to tell people that `takeUntil` should generally be placed last. That's the general rule of thumb, but if you needed a `toArray` - or something else that depends on a `complete` notification - then would need to go last (the rule accounts for this).

I think it's easier to explain that `takeUntil` is best placed last than it is to explain which operators can leak inner subscriptions if placed after the `takeUntil`. So it's not that the `tap` is unsafe, it's just not easy to explain/remember which operators are unsafe.

**Comment by willium** [comment]
Thanks for the explanation! appreciate your patience :)

**Comment by cartant** [comment]
No worries. At some stage, I'll see if I can make some changes to the docs - and/or failure messages - to better explain what's going on.
