### ISSUE TITLE
Config files

### ISSUE THREAD

**Issue by timdeschryver** [cartant/eslint-plugin-rxjs#6]
When `eslint-plugin-rxjs` is installed we have to add rules manually to the `eslint` config. Would it make sense to provide default configs where we define rules? For example a config file with all the rules and/or a config file with recommended rules.

An example:

1) [Define the config file](https://github.com/timdeschryver/eslint-plugin-ngrx/blob/master/src/configs/recommended.json)
2) [Export the defined config(s)](https://github.com/timdeschryver/eslint-plugin-ngrx/blob/master/src/index.ts#L8)

To use the config file:

```
module.exports = {
  "plugins": ["rxjs"],
  "extends": [
    "plugin:rxjs/recommended",
  ]
}
```

**Comment by cartant** [comment]
Yes, it will make sense to have a recommended config. I cannot see an all-rules config being useful, though, as some of the rules will be contradictory.

**Comment by cartant** [comment]
As mentioned in comments made against PRs, I think there is some merit in having a recommended rule set and a strict rule set. We can decide what's what once the conversion is complete.
