### ISSUE TITLE
[no-implicit-any-catch] fixer produces invalid code

### ISSUE THREAD

**Issue by rafaelss95** [cartant/eslint-plugin-rxjs#62]
**Before**:
```
.pipe(
  catchError(error => {}),
)
```

**After fix**:
```
.pipe(
  catchError(error: unknown => {}), // compilation errors
)
```

It looks like this line should perform some checks before adding `: unknown`:
https://github.com/cartant/eslint-plugin-rxjs/blob/ebfb553815d38362341d9b7d382b378c858e7321/source/rules/no-implicit-any-catch.ts#L116

**Comment by cartant** [comment]
Should be fixed in 3.0.1.
