### ISSUE TITLE
Add an option to enforce subscription variable names using finnish rule

### ISSUE THREAD

**Issue by dev054** [cartant/eslint-plugin-rxjs#63]
First point is that I noticed that the project I'm currently working on has two standards for "Subscription" declarations: one that uses `finnish` notation and others that don't, so I'd like to propose the addition of this option in `finnish` rule.

A trivial case that I'm seeing much is the use with `@ngrx / component-store`, which generally looks like this:

```
class MyStore extends ComponentStore<State> {
  // `myEffect` is typed as `Subscription`.
  readonly myEffect = this.effect(trigger$ => trigger$.pipe())
}
```

In this case, I'd like to enforce `myEffect` to be `myEffect$`.
Maybe it could be useful to implements it also in `no-finnish` so other teams can **avoid** this notation even for `Subscription`.

The second point is another thing that I also noticed that sometimes the `finnish` notation is misused, for example in places that do not use Observables or something like that, but I don't know if it's in the scope of this rule.

**Comment by cartant** [comment]
I don't use Angular or NgRx these days, so you'll need to tell me what the return type of the `this.effect` call is. Is it an `Observable`?

**Comment by timdeschryver** [comment]
I don't think this makes sense. 
A component store effect is just a method that returns a `void` or a `Subscription`, the return type of the attached snipped would be `const myEffect: () => void`.

**Comment by dev054** [comment]
Well, yeah to make it return a `Subscription` we would just need to add the generic to it, but that isn't the point, it was just a sample. The fact is that the proposal is to enforce the `finnish` **also** for `Subscription` (remember that users can always have it enabled or not, depending on its project standards).

Another sample:

```
readonly ok$ = this.test$.subscribe();
readonly notOk= this.test$.subscribe();
```

**Comment by cartant** [comment]
No, sorry. I don't want to implement an option to do that, as using the `$` suffix for subscriptions is not what Finnish notation is about.

**Comment by dev054** [comment]
Ok, thanks :)

**Comment by dev054** [comment]
> The second point is another thing that I also noticed that sometimes the `finnish` notation is misused, for example in places that do not use Observables or something like that, but I don't know if it's in the scope of this rule.

Btw, any chance to have this addressed or not also?

**Comment by cartant** [comment]
> ... any chance to have this addressed

Yeah, that might be addressable. That's why I didn't close the issue. 🙂

**Comment by cartant** [comment]
In 3.1.0, the `finnish` rule now has a `strict` option that will effect failures for non-`Observable` identifiers that have a `$` suffix.
