### ISSUE TITLE
no-unsafe-takeuntil not working if referencing an observable from another object

### ISSUE THREAD

**Issue by j0hnwhyte** [cartant/eslint-plugin-rxjs#64]
In an Angular 10 project, I have a component with a constructor:
```typescript
  constructor(
    private ss: MyService, // Injected by Angular
  ) {
    ss.s1.asObservable().pipe(
      takeUntil(this.destroyed$), // ESLint Error not notified
      tap(),
    ).subscribe();

    const s2 = new Subject()

    s2.asObservable().pipe(
      takeUntil(this.destroyed$), // ESLint Error notified
      tap(),
    ).subscribe();
```

MyService has in its definition:
```typescript
export class MyService {
  s1 = new Subject()
``` 

As commented, the rule won't work if I reference the Subject from another file.

**Comment by cartant** [comment]
> ... the rule won't work if I reference the Subject from another file

I cannot see how this could be an issue with the rule, as the rule doesn't care about the form of the `pipe` call expression. It only cares about the call's arguments and [whether or not the call's return type could be an `Observable`](https://github.com/cartant/eslint-plugin-rxjs/blob/bd63c34f41e38396a9539fe273de14bc6225db33/source/rules/no-unsafe-takeuntil.ts#L89-L95).

My guess would be that there is an issue with your linting configuration and it is unable to compile your project without error. The linter's TypeScript infrastructure won't report errors; it'll just keep on going, but without the types. And if it doesn't have the types, `couldBeObservable` will return `false` and the rule won't be enforced.

It's up to you to investigate your linter config. There is nothing I can do here.

**Comment by j0hnwhyte** [comment]
Thanks for looking into this, but if that was the case, how can it, in the same file, show an error in the second line and not in the first? Wouldn't it fail for the entire file?
I'm not very practical with linters, so in case I'd just leave this.

**Comment by cartant** [comment]
Because it's likely that the import doesn't have type information but the same-file declaration does. E.g. that's what would happen if the import location had a typo and referred to a file that didn't exist. The linter would not complain.

**Comment by j0hnwhyte** [comment]
I see. So maybe the angular compiler can resolve the import but the linter can't, and that's what you refer as a configuration mistake, is that it?

**Comment by cartant** [comment]
Yeah. The linter uses the TypeScript parser which uses the compiler if a `project` is specified in the `parserOptions` but said compilation ignores errors, so unresolvable imports will be deemed `any`. I don't use Angular (anymore), so IDK anything about it's configuration.

**Comment by j0hnwhyte** [comment]
AHA! That was the fault, in my project I use the `compilerOptions.paths` to create absolute resolution paths in imports, but that happens in `src/tsconfig.app.json` rather than in the root `tsconfig.json`. In the moment I replaced the `import {..}  from "@app/my/path"` to `import {...} from "../../my/path"` it worked immediately.

Thanks a lot for the clarification, this was really helpful.

**Comment by cartant** [comment]
No worries. Glad it working for you.
