### ISSUE TITLE
`no-ignored-subscribe` may also support `Subscribable`

### ISSUE THREAD

**Issue by dubzzz** [cartant/eslint-plugin-rxjs#69]
Hi,

First of all thanks a lot for this project. I'm not sure the issue is really an issue. Before trying to suggest a fix I wanted to make sure that the idea was relevant.

Today, the rule `no-ignored-subscribe` only checks the ignored `subscribe` for `Observable`. See https://github.com/cartant/eslint-plugin-rxjs/blob/main/source/rules/no-ignored-subscribe.ts#L28

But it seems that ideally it should check ignored `subscribe` for any `Subscribable` (an `Observable` is a `Subscribable`). What's your opinion?

**Comment by cartant** [comment]
Do you have a use case for this? I.e. an example of someplace that user-land code would be subscribing to a `Subscribable`? If not, I'm inclined to leave it as it is, for the moment. At least until [this issue](https://github.com/ReactiveX/rxjs/issues/5909) is discussed/resolved.

**Comment by dubzzz** [comment]
Not anything in a public repository unfortunately.

Why `Subscribable` and not `Observable`?

I have a function that creates instances of `Observable` but from an user point of view I only wanted to expose a minimal subset of the API: the `Subscribable` part (basically typings only).

Let's take an example with something close:
```ts
function useWatch<T>($s: Observable<T>): T | undefined {
  const [value, setValue] = useState<T>();
  useEffect(() => {
    const s = $s.subscribe(setValue);
    return () => s.unsubsribe();
  }, [$s]);
  return value;
}
```

From a caller point of view this constraint on `Observable` could be relaxed. Any `Subscribable` would work with this code. Additionally the smaller the size of the input type the simpler it is to mock in the tests.

**Comment by cartant** [comment]
https://github.com/cartant/eslint-plugin-rxjs/blob/main/CHANGELOG.md#320-2021-04-25

**Comment by dubzzz** [comment]
Thanks a lot 😁
