### ISSUE TITLE
[feature request] `prefer-rxjs` replace `rxjs/operators` with `rxjs` 

### ISSUE THREAD

**Issue by JounQin** [cartant/eslint-plugin-rxjs#77]
See https://github.com/ReactiveX/rxjs/pull/6488

**Comment by cartant** [comment]
A rule that flags imports from `"rxjs/operators"` as failures would be very easy, but writing fixers for rules is somewhat tedious. I'll probably add this eventually, but it's not near the top of my list of things to do.

**Comment by JounQin** [comment]
I finish up by using core rule [`no-restricted-imports`](https://eslint.org/docs/rules/no-restricted-imports)

```json
{
  "rules": {
    "no-restricted-imports": [
      2,
      {
        "paths": [
          {
            "name": "rxjs/operators",
            "message": "Please use top level `rxjs` directly instead."
          }
        ]
      }
    ]
  }
}
```
