### ISSUE TITLE
ESLint 8.0.0

### ISSUE THREAD

**Issue by oBusk** [cartant/eslint-plugin-rxjs#84]
## [Breaking changes for plugin developers](https://eslint.org/docs/8.0.0/user-guide/migrating-to-8.0.0#breaking-changes-for-plugin-developers)

* [Node.js 10, 13, and 15 are no longer supported](https://eslint.org/docs/8.0.0/user-guide/migrating-to-8.0.0#drop-old-node)
* [Rules require `meta.hasSuggestions` to provide suggestions](https://eslint.org/docs/8.0.0/user-guide/migrating-to-8.0.0#suggestions)
* [Rules require `meta.fixable` to provide fixes](https://eslint.org/docs/8.0.0/user-guide/migrating-to-8.0.0#fixes)
* [`SourceCode#getComments()` fails in `RuleTester`](https://eslint.org/docs/8.0.0/user-guide/migrating-to-8.0.0#get-comments)
* [Changes to shorthand property AST format](https://eslint.org/docs/8.0.0/user-guide/migrating-to-8.0.0#ast-format)

**Comment by cartant** [comment]
https://github.com/cartant/eslint-plugin-rxjs/blob/main/CHANGELOG.md#400-2021-10-17
