### ISSUE TITLE
[BUG] rxjs/no-ignored-takewhile-value does not recognise destructuring

### ISSUE THREAD

**Issue by gultyaev** [cartant/eslint-plugin-rxjs#93]
![image](https://user-images.githubusercontent.com/22374911/149107616-05a43684-3b1f-4b39-9878-45abe327f6bd.png)
![image](https://user-images.githubusercontent.com/22374911/149107688-d5ee38aa-357c-4f7e-90c6-6a0c34948050.png)

I expect the error not to be there as clearly the value is being used.

Using the latest version of the plugin

**Comment by cartant** [comment]
Should be fixed in 5.0.1.
