### ISSUE TITLE
You have used a rule which requires parserServices to be generated. You must therefore provide a value for the "parserOptions.project" property for @typescript-eslint/parser.

### ISSUE THREAD

**Issue by cathey191** [cartant/eslint-plugin-rxjs#97]
When running linting I'm getting the below error.
Is there a fix for this?

 `Error: Error while loading rule 'rxjs/no-unsafe-takeuntil': You have used a rule which requires parserServices to be generated. You must therefore provide a value for the "parserOptions.project" property for @typescript-eslint/parser.`

`
{
    "root": true,
    "parser": "@typescript-eslint/parser",
    "plugins": [
        "rxjs"
    ],
    "overrides": [{
            "files": "src/app/**/*.ts",
            "rules": {
                "rxjs/no-unsafe-takeuntil": "error"
            },
            "excludedFiles": ["**/*.spec.ts", "**/*.page.ts"]
        }
    ]
}`

**Comment by cathey191** [comment]
Fixed with:
`"parserOptions": {
        "project": [ "tsconfig.json"]
    },`

**Comment by jokezer** [comment]
This is working with NX:

```
...
    {
      files: ['*.ts', '*.tsx'],
      parserOptions: {
        project: ['tsconfig.?*.json'],
      },
      extends: [
        'plugin:rxjs/recommended',
      ],
      rules: {}
    },
    {
      files: ['*.js', '*.jsx'],
      extends: ['plugin:@nrwl/nx/javascript'],
...
```
